# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_auto_20170902_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='user',
        ),
        migrations.AddField(
            model_name='translation',
            name='date_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
